fifth module completed
js-tasks-ru/jsbasic-20211108_aleksandr-matveev7 pull request #7
Opened 2021-12-01 18:16 UTC by AlrMatveev

2021-12-02 17:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-02 21:31 UTC, SinimaWath requested changes

2021-12-02 21:31 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  button.addEventListener('click', () => text.getAttribute('hidden') == '' ? text.hidden = false : text.hidden = true);
Вместо проверки `text.getAttribute('hidden')`, можно использовать: `text.hidden ? `, так как это стандартный артибут

2021-12-05 12:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-05 12:00 UTC, AlrMatveev commented on 5-module/2-task/index.js
> +  button.addEventListener('click', () => text.getAttribute('hidden') == '' ? text.hidden = false : text.hidden = true);
исправил

2021-12-05 15:55 UTC, SinimaWath approved these changes
все круто!

2021-12-05 15:56 UTC, merged